In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import time
import scipy as sc
from scipy.spatial.distance import pdist, squareform
from itertools import combinations
from scipy import stats
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier

In [3]:
def kerval(a, b, p = 3):
    #Polunomial kernel
    return (a.T@b)**p

#check if this is even used
def mysign(x):
    if x <= 0:
        return -1
    else:
        return 1
    
#sign to create array for real y used in the multiclass perceptron
def mysign2(x):
    check = (x<=0)
    n = x.shape[0]
    new_x = np.ones([n])
    new_x[check] = -1
    
    return new_x

# a function to shuffle data randomly
def shuffling(data):
    rng = np.random.default_rng()
    rng.shuffle(data, axis=0)
    return data

# to generate an array of zeros for alpha of perceptron
def clearClass(data,numb_class = 3):
    return np.zeros((numb_class, data.shape[0]))

#a function for generating different folds for cross validation
def cross_data(data,folds):
    folds = int(folds)
    #data = np.loadtxt(path)
    
    rng = np.random.default_rng()

    rng.shuffle(data, axis=0)
    num = int(data.shape[0]/folds)
    folds_Arr = np.zeros([folds,num,int(data.shape[1])])
    #m = data.shape[0]
    bound_prev = 0
    bound_current = 0
    #print("shape",data.shape)
    for a in range(folds):
        bound_current += num
        #print(a)
        #print(bound_prev ,bound_current)
        folds_Arr[a] = data[bound_prev:bound_current]
        bound_prev = bound_current
    
    return folds_Arr

# a function to split data 80 train 20 test
def train_test_split(datas):
    data = datas

    rng = np.random.default_rng()

    rng.shuffle(data, axis=0)
    #print(data.shape)

    m = data.shape[0]

    train = data[0:int(m*0.8)]
    test = data[int(0.8*m):]

    return train, test

# a function to check with the test data and produce error rate
def testClass3(data,test_data,classifiers,numb_class,d,kernel_result):
    mistakes = 0
    preds = np.zeros((numb_class))
    maxi = 0
    for i in range(test_data.shape[0]):
        preds = (classifiers@kernel_result[i].reshape(-1,1)).T[0]
        
        y_pred = np.argmax(preds)
        y_true = int(test_data[i,0])   
        if y_pred != y_true:
            mistakes+=1
    # error rate test sample
    return mistakes/test_data.shape[0]

# a function to check with test data and produce error rate for
# shld change name later on
def testClass31(data,test_data,classifiers,numb_class,d,kernel_result):
    mistakes = 0
    preds = np.zeros((numb_class))
    maxi = 0
    confu = np.zeros([numb_class,numb_class])
    for i in range(test_data.shape[0]):
        preds = (classifiers@kernel_result[i].reshape(-1,1)).T[0]
        
        y_pred = np.argmax(preds)
        y_true = int(test_data[i,0])   
        if y_pred != y_true:
            confu[int(y_pred),int(y_true)] +=1
            mistakes+=1
        #print("mistakes",mistakes,y_pred,y_true)
    return mistakes,confu

#a training function to learn from training set and produce alphas required for
def traingen23(data, classifiers,numb_class , d,kernel_result):
    mistakes = 0
    preds = np.zeros((numb_class))
    maxi = 0
    
    for i in range(data.shape[0]):

     
        preds = (classifiers@kernel_result[i].reshape(-1,1)).T[0]

        #print("preds",preds.shape)

        y_pred = np.argmax(preds)
        y_true = int(data[i,0])

        Y_true = np.ones(numb_class)*-1
        Y_true[y_true] = 1

        y_mistakes = ((preds*Y_true) <= 0)
        #print(y_mistakes.shape)

        classifiers[y_mistakes, i] = classifiers[y_mistakes, i] - mysign2(preds[y_mistakes])  

        if y_pred != y_true:
            mistakes+=1
        
            
    return mistakes/data.shape[0], classifiers



<h3> SVM <h3>

In [4]:
def point2(i1,m):
    i2 = np.random.choice(m)
    while i1 == i2:
        i2 = np.random.choice(m)

    return i2

In [5]:
#latest svm implementation
def SMO(X, y, C,K ):
    tol=10e-2
    max_passes=10
    rand_no_prog = 0
    m = X.shape[0]
    alphas = np.zeros((m))
#     old_alphas = np.zeros((m))
    b = 0
    E = np.ones((m))*(-y)

#     K = (X @ X.T) ** d
    # kernel = lambda xi, yi: (np.dot(xi.T, yi)) ** d

    passes = 0
    time_out = 0
    while (passes < max_passes) and (time_out < 10):
        #print("time",time_out)
        num_changed_alphas = 0
        for i in range(m):
            rand_no_prog = 0
            #print("iterate",i)
            
            E[i] = alphas * y @ K[i, :] + b - y[i]

            # E[i] = np.sum(alphas*y*kernel(X.T, X[i,:])) + b - y[i]

            if (y[i]*E[i] < -tol and alphas[i] < C)\
            or (y[i]*E[i] > tol and alphas[i] > 0): 

                while rand_no_prog < 5:
                    #print(f"progress {rand_no_prog}, iter{i}")

                    j = point2(i,m)



                    E[j] = (alphas * y) @K[j, :] + b - y[j]


                    if y[i] != y[j]:
                        L = max(0, alphas[j] - alphas[i])
                        H = min(C, C + alphas[j] - alphas[i])

                    else:
                        L = max(0, alphas[i] + alphas[j] - C)
                        H = min(C, alphas[i] + alphas[j])

                    if L == H:
                        rand_no_prog +=1
                        continue

                    eta = 2*K[i, j] - K[i, i] - K[j, j]
                    # eta = 2*kernel(X[i,:], X[j,:]) - kernel(X[i,:], X[i,:]) - kernel(X[j,:], X[j,:])

                    if eta >= 0:
                        rand_no_prog +=1
                        continue

                    # Compute alpha_j
                    alphasj = alphas[j] - (y[j]*(E[i] - E[j]) / eta)

                    # Clip alpha_j

                    if alphasj > H:
                        alphasj = H
                    elif alphasj < L:
                        alphasj = L
                    # Note: alpha_j is unchanged if L<=alpha_j<=H as desired

                    if abs(alphasj - alphas[j]) < 10e-100:
                        rand_no_prog +=1
                        #print("no progress")
                        continue

                    alphasi = alphas[i] + (y[i] * y[j] * (alphas[j] - alphasj))

                    b1 = b - E[i] - (y[i]*(alphasi - alphas[i])*K[i,i]) - (y[j]*(alphasj - alphas[j])*K[i,j])
                    # b1 = b - E[i] - y[i]*(alphas[i] - old_alpha_i)*kernel(X[i,:], X[i,:]) - y[j]*(alphas[j] - old_alpha_j)*kernel(X[i,:], X[j,:])

                    b2 = b - E[j] - (y[i]*(alphasi - alphas[i])*K[i,j]) - (y[j]*(alphasj - alphas[j])*K[j,j])
                    
                    alphas[i] = alphasi
                    alphas[j] = alphasj
                    if (alphas[i] > 0) and (alphas[i] < C):
                        b = b1
                    elif (alphas[j] > 0) and (alphas[j] < C):
                        b = b2
                    else:
                        b = (b1 + b2) / 2

                    num_changed_alphas += 1
                    #exit loop to change i1 or first point
                    rand_no_prog = 1000

                    
                    
                    
            
            # print("i error: ", E[i], "j error: ", E[j])
        if num_changed_alphas == 0:
            passes += 1
        else:
            passes = 0
        
        time_out += 1
    
    return alphas, b, E

In [6]:
def train_svm(combi,train,d,c):
    a = []
    betas = np.zeros([45,1])
    time_start = time.time()

    for i,comb in enumerate(combi):

        label0 = comb[0] # +1
        label1 = comb[1] # -1

        picked_1 = (train[:,0] == label1)
        picked_0 = (train[:,0] == label0)


        samples = np.logical_or(picked_1, picked_0)

        index_label1 = np.where(picked_1 == True)[0]
        index_label0 = np.where(picked_0 == True)[0]

        train_1 = train[index_label1]
        train_0 = train[index_label0]
        train_1[:,0] = -1
        train_0[:,0] = 1
        non_index = np.where(samples == False)[0]
        data_train = np.concatenate([train_0, train_1], axis = 0)

        small_x = data_train[:,1:]
        small_y = data_train[:,0]


        small_kernel = kerval(small_x.T, small_x.T, d)

        aresult,betas[i],Eresult = SMO(small_x, small_y,c,small_kernel )
        a.append(aresult)


    print("time taken training", time.time()-time_start)
    return a, betas

In [7]:
def pred_class(pred_vals, combo):

    which_class = 1* (pred_vals <= 0) 
    classifier_preds = combo[np.arange(combo.shape[0]), which_class]
    
#     # Count class votes
#     unique, counts = np.unique(classifier_preds, return_counts = True)
    
#     # Prediction is just maximum counted class
#     pred_lab = unique[np.argmax(counts)]

    pred_lab = stats.mode(classifier_preds)[0][0]
    
    return pred_lab

In [8]:
def preds_data(combi,kernel_test,test,train,a,betas):
    preds_data = np.zeros([test.shape[0],45])
    start_time = time.time()
    for i,a_val in enumerate(a):
        combi_curr = combi[i]
        label0 = combi_curr[0] # +1
        label1 = combi_curr[1] # -1
        #print()
        #print("label",label0,label1)

        picked_1 = (train[:,0] == label1)
        picked_0 = (train[:,0] == label0)
        #print("sum",np.sum(picked_0)+np.sum(picked_1))


#         samples = np.logical_or(picked_1, picked_0)

        index_label1 = np.where(picked_1 == True)[0]
        index_label0 = np.where(picked_0 == True)[0]
        train_1 = train[index_label1]
        train_0 = train[index_label0]
        train_1[:,0] = -1
        train_0[:,0] = 1
        data_label = np.concatenate([index_label0, index_label1], axis = 0)
        small_y = np.concatenate([train_0[:,0], train_1[:,0]], axis = 0)

        kern_relevant = kernel_test[data_label]
        alpha = np.array(a_val)

        pred = (alpha*small_y).reshape(1,-1)@kern_relevant + betas[i]
        preds_data[:,i] = np.sign(pred.reshape(-1))
    print("time taken predicting", time.time() - start_time)
    return preds_data

In [ ]:
# trial code to determine range of c
#power above 1 has no effect
#power below 10-5 produce result that is very bad
cset = np.array([10.0**(-4),10.0**(-3),10.0**(-2), 1])
path_real_data = "./zipcombo.dat"
datas = np.loadtxt(path_real_data)
m,n = datas.shape
iteration = 1
diffDs = np.arange(1,2,1)
error_sum_svm_trial = np.zeros([iteration , len(diffDs) , len(cset) ,2])
cValues = np.array([10**(50),1,10**(-50)])
time_total = time.time()
for iters in range (iteration):
    train,test = train_test_split(datas)
    time_inter = time.time()
    for dindex, d in enumerate(diffDs):
        for cindex, c in enumerate(cset):
            print(f"d {d}, c {c}, iter {iters}")
            time_d = time.time()
            combi = list (combinations(range(10),2))

            a, betas = train_svm(combi,train,d,c)

            kernel_test = kerval(train[:,1:].T, test[:,1:].T, d)
            pred_result = preds_data(combi,kernel_test,test,train,a,betas)

            pred_final = np.zeros([test.shape[0]])
            for i,pred_data in enumerate(pred_result):
                pred_final[i] = pred_class(pred_data, np.array(combi))

            avg_test_err = np.mean(pred_final != test[:,0])
            kernel_train = kerval(train[:,1:].T, train[:,1:].T, d)
            pred_result = preds_data(combi,kernel_train,train,train,a,betas)

            pred_final = np.zeros([train.shape[0]])
            for i,pred_data in enumerate(pred_result):
                pred_final[i] = pred_class(pred_data, np.array(combi))
            avg_train_err = np.mean(pred_final != train[:,0])
            error_sum_svm_trial[iters,dindex,cindex] = np.array([avg_train_err,avg_test_err])
            print(f"print train and test error {avg_train_err} and {avg_test_err} ")
            print(f"time to run {d} d",time.time() - time_d)
    print(f"iteration {iters}",time.time()-time_inter)
print("total time", time.time()-time_total)

In [13]:
# trial code to determine range of c
#power above 1 has no effect
#power below 10-5 produce result that is very bad
cset = np.array([10.0**(-3),10.0**(-2), 1])
path_real_data = "./zipcombo.dat"
datas = np.loadtxt(path_real_data)
m,n = datas.shape
iteration = 1
diffDs = np.arange(1,2,1)
error_sum_svm_trial = np.zeros([iteration , len(diffDs) , len(cset) ,2])
time_total = time.time()
for iters in range (iteration):
    train,test = train_test_split(datas)
    time_inter = time.time()
    for dindex, d in enumerate(diffDs):
        for cindex, c in enumerate(cset):
            print(f"d {d}, c {c}, iter {iters}")
            time_d = time.time()
            combi = list (combinations(range(10),2))

            a, betas = train_svm(combi,train,d,c)

            kernel_test = kerval(train[:,1:].T, test[:,1:].T, d)
            pred_result = preds_data(combi,kernel_test,test,train,a,betas)

            pred_final = np.zeros([test.shape[0]])
            for i,pred_data in enumerate(pred_result):
                pred_final[i] = pred_class(pred_data, np.array(combi))

            avg_test_err = np.mean(pred_final != test[:,0])
            kernel_train = kerval(train[:,1:].T, train[:,1:].T, d)
            pred_result = preds_data(combi,kernel_train,train,train,a,betas)

            pred_final = np.zeros([train.shape[0]])
            for i,pred_data in enumerate(pred_result):
                pred_final[i] = pred_class(pred_data, np.array(combi))
            avg_train_err = np.mean(pred_final != train[:,0])
            error_sum_svm_trial[iters,dindex,cindex] = np.array([avg_train_err,avg_test_err])
            print(f"print train and test error {avg_train_err} and {avg_test_err} ")
            print(f"time to run {d} d",time.time() - time_d)
    print(f"iteration {iters}",time.time()-time_inter)
print("total time", time.time()-time_total)

d 1, c 0.001, iter 0
time taken training 14.491607427597046
time taken predicting 0.4802680015563965
time taken predicting 1.6069791316986084
print train and test error 0.05229900510890024 and 0.060215053763440864 
time to run 1 d 18.51906180381775
d 1, c 0.01, iter 0
time taken training 14.928883790969849
time taken predicting 0.45079636573791504
time taken predicting 1.681509256362915
print train and test error 0.026888948642108095 and 0.05 
time to run 1 d 19.003029346466064
d 1, c 1.0, iter 0
time taken training 16.298166275024414
time taken predicting 0.49165940284729004
time taken predicting 1.6238343715667725
print train and test error 0.028098951331002958 and 0.06344086021505377 
time to run 1 d 20.404479026794434
iteration 0 57.92657017707825
total time 57.94450235366821


In [14]:
# main run
#power above 1 has no effect
#power below 10-5 produce result that is very bad
cset = np.array([10.0**(-3),10.0**(-2), 1])
path_real_data = "./zipcombo.dat"
datas = np.loadtxt(path_real_data)
m,n = datas.shape
iteration = 20
diffDs = np.arange(1,8,1)
error_sum_svm_trial = np.zeros([iteration , len(diffDs) , len(cset) ,2])

time_total = time.time()
for iters in range (iteration):
    train,test = train_test_split(datas)
    time_inter = time.time()
    for dindex, d in enumerate(diffDs):
        for cindex, c in enumerate(cset):
            print(f"d {d}, c {c}, iter {iters}")
            time_d = time.time()
            combi = list (combinations(range(10),2))

            a, betas = train_svm(combi,train,d,c)

            kernel_test = kerval(train[:,1:].T, test[:,1:].T, d)
            pred_result = preds_data(combi,kernel_test,test,train,a,betas)

            pred_final = np.zeros([test.shape[0]])
            for i,pred_data in enumerate(pred_result):
                pred_final[i] = pred_class(pred_data, np.array(combi))

            avg_test_err = np.mean(pred_final != test[:,0])
            kernel_train = kerval(train[:,1:].T, train[:,1:].T, d)
            pred_result = preds_data(combi,kernel_train,train,train,a,betas)

            pred_final = np.zeros([train.shape[0]])
            for i,pred_data in enumerate(pred_result):
                pred_final[i] = pred_class(pred_data, np.array(combi))
            avg_train_err = np.mean(pred_final != train[:,0])
            error_sum_svm_trial[iters,dindex,cindex] = np.array([avg_train_err,avg_test_err])
            print(f"print train and test error {avg_train_err} and {avg_test_err} ")
            print(f"time to run {d} d",time.time() - time_d)
    print(f"iteration {iters}",time.time()-time_inter)
print("total time", time.time()-time_total)

d 1, c 0.001, iter 0
time taken training 15.56591510772705
time taken predicting 0.5136313438415527
time taken predicting 1.8480870723724365
print train and test error 0.049475665501478895 and 0.06827956989247312 
time to run 1 d 20.06690740585327
d 1, c 0.01, iter 0
time taken training 16.228090047836304
time taken predicting 0.4906904697418213
time taken predicting 1.699038028717041
print train and test error 0.028098951331002958 and 0.054838709677419356 
time to run 1 d 20.4732985496521
d 1, c 1.0, iter 0
time taken training 16.31690740585327
time taken predicting 0.47300100326538086
time taken predicting 1.6964428424835205
print train and test error 0.033476741059424574 and 0.07688172043010753 
time to run 1 d 20.531322240829468
d 2, c 0.001, iter 0
time taken training 16.056121110916138
time taken predicting 0.5156266689300537
time taken predicting 1.7134246826171875
print train and test error 0.0010755579456843238 and 0.035483870967741936 
time to run 2 d 20.39606547355652
d 2, c

time taken training 19.178788900375366
time taken predicting 0.476729154586792
time taken predicting 1.6904776096343994
print train and test error 0.00026888948642108095 and 0.024731182795698924 
time to run 5 d 25.92455554008484
d 5, c 0.01, iter 1
time taken training 19.13341212272644
time taken predicting 0.48369550704956055
time taken predicting 1.7083897590637207
print train and test error 0.00013444474321054048 and 0.020967741935483872 
time to run 5 d 25.897305250167847
d 5, c 1.0, iter 1
time taken training 20.498961448669434
time taken predicting 0.5005841255187988
time taken predicting 1.6864662170410156
print train and test error 0.00040333422963162143 and 0.021505376344086023 
time to run 5 d 27.231428384780884
d 6, c 0.001, iter 1
time taken training 18.99177360534668
time taken predicting 0.47274255752563477
time taken predicting 1.7054457664489746
print train and test error 0.00026888948642108095 and 0.024731182795698924 
time to run 6 d 25.752746105194092
d 6, c 0.01, i

time taken predicting 1.7173876762390137
print train and test error 0.0008066684592632429 and 0.02849462365591398 
time to run 2 d 19.438494443893433
d 2, c 0.01, iter 3
time taken training 15.143767833709717
time taken predicting 0.5018091201782227
time taken predicting 1.799274206161499
print train and test error 0.0 and 0.030107526881720432 
time to run 2 d 19.52729344367981
d 2, c 1.0, iter 3
time taken training 15.219273567199707
time taken predicting 0.4837150573730469
time taken predicting 1.6627376079559326
print train and test error 0.00040333422963162143 and 0.032795698924731186 
time to run 2 d 19.364097118377686
d 3, c 0.001, iter 3
time taken training 18.536332607269287
time taken predicting 0.4417698383331299
time taken predicting 1.6815013885498047
print train and test error 0.00013444474321054048 and 0.027419354838709678 
time to run 3 d 24.820382595062256
d 3, c 0.01, iter 3
time taken training 18.541146516799927
time taken predicting 0.4637331962585449
time taken pred

time taken training 18.130388259887695
time taken predicting 0.4517648220062256
time taken predicting 1.6760704517364502
print train and test error 0.00026888948642108095 and 0.026881720430107527 
time to run 6 d 24.42252540588379
d 6, c 1.0, iter 4
time taken training 18.093058109283447
time taken predicting 0.45174312591552734
time taken predicting 1.8346295356750488
print train and test error 0.00026888948642108095 and 0.025806451612903226 
time to run 6 d 24.86864423751831
d 7, c 0.001, iter 4
time taken training 21.062158584594727
time taken predicting 0.45973968505859375
time taken predicting 1.8777408599853516
print train and test error 0.00013444474321054048 and 0.03494623655913978 
time to run 7 d 27.93925929069519
d 7, c 0.01, iter 4
time taken training 20.44521427154541
time taken predicting 0.4417724609375
time taken predicting 2.2232723236083984
print train and test error 0.00013444474321054048 and 0.032795698924731186 
time to run 7 d 27.868155241012573
d 7, c 1.0, iter 4

time taken training 18.55628228187561
time taken predicting 0.4820382595062256
time taken predicting 1.6954941749572754
print train and test error 0.00013444474321054048 and 0.021505376344086023 
time to run 3 d 24.87708067893982
d 3, c 1.0, iter 6
time taken training 18.608316898345947
time taken predicting 0.49025893211364746
time taken predicting 1.7163057327270508
print train and test error 0.00026888948642108095 and 0.02258064516129032 
time to run 3 d 25.092225790023804
d 4, c 0.001, iter 6
time taken training 18.857666492462158
time taken predicting 0.4734079837799072
time taken predicting 1.7368824481964111
print train and test error 0.00013444474321054048 and 0.02043010752688172 
time to run 4 d 25.22893500328064
d 4, c 0.01, iter 6
time taken training 18.62702775001526
time taken predicting 0.46581292152404785
time taken predicting 1.7104344367980957
print train and test error 0.00040333422963162143 and 0.01935483870967742 
time to run 4 d 24.969865560531616
d 4, c 1.0, iter 

time taken training 18.05505108833313
time taken predicting 0.47771263122558594
time taken predicting 1.7169599533081055
print train and test error 0.00026888948642108095 and 0.030107526881720432 
time to run 7 d 24.420170783996582
d 7, c 1.0, iter 7
time taken training 18.01121759414673
time taken predicting 0.5225701332092285
time taken predicting 1.7123520374298096
print train and test error 0.00013444474321054048 and 0.03064516129032258 
time to run 7 d 24.514894008636475
iteration 7 485.98174381256104
d 1, c 0.001, iter 8
time taken training 13.760380268096924
time taken predicting 0.49623560905456543
time taken predicting 1.7314138412475586
print train and test error 0.05189567087926862 and 0.06290322580645161 
time to run 1 d 17.931522369384766
d 1, c 0.01, iter 8
time taken training 14.657339096069336
time taken predicting 0.49184322357177734
time taken predicting 1.7006912231445312
print train and test error 0.027023393385318634 and 0.0467741935483871 
time to run 1 d 18.82168

time taken training 18.177878618240356
time taken predicting 0.4697418212890625
time taken predicting 1.730921745300293
print train and test error 0.00013444474321054048 and 0.020967741935483872 
time to run 4 d 24.504376888275146
d 4, c 1.0, iter 9
time taken training 18.384939193725586
time taken predicting 0.4867103099822998
time taken predicting 1.741335391998291
print train and test error 0.00026888948642108095 and 0.023655913978494623 
time to run 4 d 24.766651391983032
d 5, c 0.001, iter 9
time taken training 17.941455364227295
time taken predicting 0.4717371463775635
time taken predicting 1.7433383464813232
print train and test error 0.00026888948642108095 and 0.020967741935483872 
time to run 5 d 24.408048152923584
d 5, c 0.01, iter 9
time taken training 18.21547555923462
time taken predicting 0.4786839485168457
time taken predicting 1.7086832523345947
print train and test error 0.00040333422963162143 and 0.023655913978494623 
time to run 5 d 24.57403540611267
d 5, c 1.0, iter

time taken predicting 0.4896659851074219
time taken predicting 1.7144973278045654
print train and test error 0.029174509276687282 and 0.0489247311827957 
time to run 1 d 18.68281388282776
d 1, c 1.0, iter 11
time taken training 15.328080654144287
time taken predicting 0.5343790054321289
time taken predicting 1.779548168182373
print train and test error 0.023796719548265663 and 0.06881720430107527 
time to run 1 d 19.660115718841553
d 2, c 0.001, iter 11
time taken training 15.379196405410767
time taken predicting 0.5036578178405762
time taken predicting 1.7673077583312988
print train and test error 0.00040333422963162143 and 0.02849462365591398 
time to run 2 d 19.602190017700195
d 2, c 0.01, iter 11
time taken training 15.360426187515259
time taken predicting 0.4783039093017578
time taken predicting 1.7335913181304932
print train and test error 0.0012100026888948643 and 0.03118279569892473 
time to run 2 d 19.5610089302063
d 2, c 1.0, iter 11
time taken training 15.565766096115112
tim

time taken training 18.103947162628174
time taken predicting 0.4796733856201172
time taken predicting 1.712632656097412
print train and test error 0.00026888948642108095 and 0.025806451612903226 
time to run 5 d 24.511027574539185
d 5, c 1.0, iter 12
time taken training 18.185750484466553
time taken predicting 0.46872711181640625
time taken predicting 1.7281112670898438
print train and test error 0.00013444474321054048 and 0.026344086021505377 
time to run 5 d 24.509482860565186
d 6, c 0.001, iter 12
time taken training 18.116235971450806
time taken predicting 0.4946441650390625
time taken predicting 1.7737174034118652
print train and test error 0.00013444474321054048 and 0.030107526881720432 
time to run 6 d 24.532070875167847
d 6, c 0.01, iter 12
time taken training 18.19668221473694
time taken predicting 0.47869086265563965
time taken predicting 1.8235251903533936
print train and test error 0.00026888948642108095 and 0.02903225806451613 
time to run 6 d 24.637626886367798
d 6, c 1.0

print train and test error 0.0006722237160527024 and 0.02849462365591398 
time to run 2 d 19.845516204833984
d 2, c 0.01, iter 14
time taken training 15.510436534881592
time taken predicting 0.4803955554962158
time taken predicting 1.788740634918213
print train and test error 0.004840010755579457 and 0.03602150537634408 
time to run 2 d 19.793846607208252
d 2, c 1.0, iter 14
time taken training 15.472883939743042
time taken predicting 0.48669934272766113
time taken predicting 1.761929988861084
print train and test error 0.0010755579456843238 and 0.03118279569892473 
time to run 2 d 19.715150594711304
d 3, c 0.001, iter 14
time taken training 18.763316869735718
time taken predicting 0.47669529914855957
time taken predicting 1.763289213180542
print train and test error 0.006050013444474321 and 0.03225806451612903 
time to run 3 d 25.18615961074829
d 3, c 0.01, iter 14
time taken training 18.953110456466675
time taken predicting 0.521564245223999
time taken predicting 1.664865255355835
pr

time taken training 18.04671549797058
time taken predicting 0.4573178291320801
time taken predicting 1.7470769882202148
print train and test error 0.0012100026888948643 and 0.01935483870967742 
time to run 6 d 24.50261425971985
d 6, c 0.01, iter 15
time taken training 18.09576964378357
time taken predicting 0.47370243072509766
time taken predicting 1.720468521118164
print train and test error 0.00013444474321054048 and 0.01881720430107527 
time to run 6 d 24.485492944717407
d 6, c 1.0, iter 15
time taken training 18.031831741333008
time taken predicting 0.46172356605529785
time taken predicting 1.714076280593872
print train and test error 0.00013444474321054048 and 0.01989247311827957 
time to run 6 d 24.49308133125305
d 7, c 0.001, iter 15
time taken training 17.980788230895996
time taken predicting 0.4876976013183594
time taken predicting 1.6864502429962158
print train and test error 0.00013444474321054048 and 0.024731182795698924 
time to run 7 d 24.317384958267212
d 7, c 0.01, iter

print train and test error 0.0021511158913686476 and 0.030107526881720432 
time to run 2 d 19.516854524612427
d 3, c 0.001, iter 17
time taken training 18.65263533592224
time taken predicting 0.48070764541625977
time taken predicting 1.7415757179260254
print train and test error 0.0005377789728421619 and 0.025806451612903226 
time to run 3 d 25.050703287124634
d 3, c 0.01, iter 17
time taken training 18.509333610534668
time taken predicting 0.45728540420532227
time taken predicting 1.7692759037017822
print train and test error 0.00026888948642108095 and 0.025806451612903226 
time to run 3 d 25.03001117706299
d 3, c 1.0, iter 17
time taken training 18.6117742061615
time taken predicting 0.48485827445983887
time taken predicting 1.75998854637146
print train and test error 0.00013444474321054048 and 0.024193548387096774 
time to run 3 d 25.010164737701416
d 4, c 0.001, iter 17
time taken training 18.213345527648926
time taken predicting 0.5046548843383789
time taken predicting 1.747358798

time taken training 18.39611029624939
time taken predicting 0.47569775581359863
time taken predicting 1.7293791770935059
print train and test error 0.00013444474321054048 and 0.023118279569892472 
time to run 6 d 24.855365991592407
d 7, c 0.001, iter 18
time taken training 18.079051971435547
time taken predicting 0.48368048667907715
time taken predicting 1.7760233879089355
print train and test error 0.00013444474321054048 and 0.025268817204301075 
time to run 7 d 24.506686687469482
d 7, c 0.01, iter 18
time taken training 18.426549434661865
time taken predicting 0.5106329917907715
time taken predicting 1.8288872241973877
print train and test error 0.00013444474321054048 and 0.024193548387096774 
time to run 7 d 25.020619869232178
d 7, c 1.0, iter 18
time taken training 18.28012704849243
time taken predicting 0.4996778964996338
time taken predicting 1.7580821514129639
print train and test error 0.00026888948642108095 and 0.024731182795698924 
time to run 7 d 24.755078315734863
iteration

In [16]:

#result processing
for dIndex, resultd in enumerate(diffDs):
    print()
    
    for cIndex,c in enumerate(cset):
        print("d = ",resultd, "c ", cset[cIndex])
        print("mean train",np.mean(error_sum_svm_trial[:,dIndex,cIndex,0]), "standard div train",np.std(error_sum_svm_trial[:,dIndex,cIndex,0]))
        print("mean test",np.mean(error_sum_svm_trial[:,dIndex,cIndex,1]), "standard div test",np.std(error_sum_svm_trial[:,dIndex,cIndex,1]))


d =  1 c  0.001
mean train 0.05239983866630815 standard div train 0.0012039187072178203
mean test 0.057016129032258056 standard div test 0.0049288937425413255
d =  1 c  0.01
mean train 0.028784619521376714 standard div train 0.003191441826920948
mean test 0.045672043010752686 standard div test 0.0045824463872363
d =  1 c  1.0
mean train 0.025914224253831674 standard div train 0.008237182115220338
mean test 0.06220430107526881 standard div test 0.01106286496138729

d =  2 c  0.001
mean train 0.0009343909653132566 standard div train 0.0009348261167527369
mean test 0.02849462365591398 standard div test 0.0038545050169752513
d =  2 c  0.01
mean train 0.0016603925786501748 standard div train 0.0017218771342393641
mean test 0.02849462365591398 standard div test 0.003185228654537338
d =  2 c  1.0
mean train 0.0012100026888948643 standard div train 0.0005767036996377311
mean test 0.029704301075268818 standard div test 0.003704901866163304

d =  3 c  0.001
mean train 0.0010285022855606345 stan

In [23]:
# Cross validation
# 5 folds cross validation
ori_train,ori_test = train_test_split(datas)
num_fold = 5
testTrain = cross_data(ori_train,num_fold)
num_iter = 20
cset = np.array([10.0**(-3),10.0**(-2), 1])
dset = np.arange(1,8,1)
bestResultSvm = np.ones([num_iter,3])
start_time_fold = time.time()
for b in range(num_iter):
    testTrain = cross_data(ori_train,num_fold)
    start_time_iter = time.time()
    for dindex, d in enumerate(dset):
        start_time_main = time.time()

        
        #train_err_rate_new = np.zeros([5,2])
        
        for cindex, c in enumerate(cset):
            errorRateTest = 0
           
            for fold in range(5):

                testFold = testTrain[fold]
                trainFold = np.delete(testTrain,fold,0)
                trainFold = trainFold.reshape(-1,257)

                

                train = trainFold
                test = testFold

                combi = list (combinations(range(10),2))
                #amin loop to predict using One vs one
                a, betas = train_svm(combi,train,d,c)

                kernel_test = kerval(train[:,1:].T, test[:,1:].T, d)
                pred_result = preds_data(combi,kernel_test,test,train,a,betas)

                pred_final = np.zeros([test.shape[0]])
                for i,pred_data in enumerate(pred_result):
                    pred_final[i] = pred_class(pred_data, np.array(combi))

                avg_test_err = np.mean(pred_final != test[:,0])
                kernel_train = kerval(train[:,1:].T, train[:,1:].T, d)
                pred_result = preds_data(combi,kernel_train,train,train,a,betas)

                pred_final = np.zeros([train.shape[0]])
                for i,pred_data in enumerate(pred_result):
                    pred_final[i] = pred_class(pred_data, np.array(combi))
                avg_train_err = np.mean(pred_final != train[:,0])
                #end of one vs one prediction
                #store value in array


                errorRateTest +=avg_test_err
                print("results ",avg_train_err, "mistakes in test",avg_test_err,"for c", c, "for d",d,"for fold ",fold,"iter ",b)
        
        

                
            avgTestErr = errorRateTest/5
            if (avgTestErr < bestResultSvm[b,2]):
                bestResultSvm[b,:] = np.array([d, c, avgTestErr])
        print("--- %s seconds ---" , (time.time() - start_time), "time for d ",d)
            
        
        
    print("--- %s seconds ---" , (time.time() - start_time_iter), "time for iter ",b)
    
print("--- %s seconds ---" , (time.time() - start_time_fold))

time taken training 10.506090879440308
time taken predicting 0.3251347541809082
time taken predicting 1.1100807189941406
results  0.05346334902488231 mistakes in test 0.05917955615332885 for c 0.001 for d 1 for fold  0 iter  0
time taken training 10.371534585952759
time taken predicting 0.3161609172821045
time taken predicting 1.1119976043701172
results  0.05514458641560188 mistakes in test 0.07128446536650974 for c 0.001 for d 1 for fold  1 iter  0
time taken training 10.60810375213623
time taken predicting 0.3122100830078125
time taken predicting 1.1349670886993408
results  0.054640215198386015 mistakes in test 0.05110961667787491 for c 0.001 for d 1 for fold  2 iter  0
time taken training 10.694396495819092
time taken predicting 0.33065295219421387
time taken predicting 1.1200430393218994
results  0.049932750504371216 mistakes in test 0.05783456624075319 for c 0.001 for d 1 for fold  3 iter  0
time taken training 10.347329378128052
time taken predicting 0.33510804176330566
time take

time taken training 13.785548448562622
time taken predicting 0.3331108093261719
time taken predicting 1.1010627746582031
results  0.0018493611297915266 mistakes in test 0.02757229320780094 for c 0.01 for d 3 for fold  1 iter  0
time taken training 13.903995037078857
time taken predicting 0.2961759567260742
time taken predicting 1.0582008361816406
results  0.0003362474781439139 mistakes in test 0.01546738399462004 for c 0.01 for d 3 for fold  2 iter  0
time taken training 14.021440505981445
time taken predicting 0.32114219665527344
time taken predicting 1.090087890625
results  0.0253866845998655 mistakes in test 0.0410221923335575 for c 0.01 for d 3 for fold  3 iter  0
time taken training 13.973357677459717
time taken predicting 0.33211326599121094
time taken predicting 1.1020252704620361
results  0.0006724949562878278 mistakes in test 0.025554808338937456 for c 0.01 for d 3 for fold  4 iter  0
time taken training 13.816987037658691
time taken predicting 0.29920315742492676
time taken p

time taken training 13.817901134490967
time taken predicting 0.3061809539794922
time taken predicting 1.1169848442077637
results  0.0003362474781439139 mistakes in test 0.014122394082044385 for c 1.0 for d 5 for fold  2 iter  0
time taken training 13.82383131980896
time taken predicting 0.3112058639526367
time taken predicting 1.1350481510162354
results  0.0003362474781439139 mistakes in test 0.03026227303295225 for c 1.0 for d 5 for fold  3 iter  0
time taken training 13.818774938583374
time taken predicting 0.3361055850982666
time taken predicting 1.1190128326416016
results  0.00016812373907195696 mistakes in test 0.02757229320780094 for c 1.0 for d 5 for fold  4 iter  0
--- %s seconds --- 2368.1752767562866 time for d  5
time taken training 13.614493608474731
time taken predicting 0.34807276725769043
time taken predicting 1.1100003719329834
results  0.0 mistakes in test 0.03227975790181574 for c 0.001 for d 6 for fold  0 iter  0
time taken training 13.987467288970947
time taken pred

results  0.05010087424344317 mistakes in test 0.06859448554135844 for c 0.001 for d 1 for fold  2 iter  1
time taken training 10.564526081085205
time taken predicting 0.3201711177825928
time taken predicting 1.095081090927124
results  0.054640215198386015 mistakes in test 0.05043712172158709 for c 0.001 for d 1 for fold  3 iter  1
time taken training 10.684629440307617
time taken predicting 0.31017136573791504
time taken predicting 1.0801143646240234
results  0.055648957632817755 mistakes in test 0.06119704102219233 for c 0.001 for d 1 for fold  4 iter  1
time taken training 11.495258808135986
time taken predicting 0.3481459617614746
time taken predicting 1.0701093673706055
results  0.02639542703429724 mistakes in test 0.05716207128446537 for c 0.01 for d 1 for fold  0 iter  1
time taken training 11.451155424118042
time taken predicting 0.31516218185424805
time taken predicting 1.1336665153503418
results  0.031102891728312036 mistakes in test 0.0363147276395427 for c 0.01 for d 1 for f

time taken predicting 0.29620838165283203
time taken predicting 1.0531857013702393
results  0.0005043712172158709 mistakes in test 0.01882985877605918 for c 0.01 for d 3 for fold  3 iter  1
time taken training 14.022071838378906
time taken predicting 0.2932157516479492
time taken predicting 1.0811107158660889
results  0.0005043712172158709 mistakes in test 0.02757229320780094 for c 0.01 for d 3 for fold  4 iter  1
time taken training 14.043010711669922
time taken predicting 0.29018497467041016
time taken predicting 1.1120319366455078
results  0.00016812373907195696 mistakes in test 0.03295225285810356 for c 1.0 for d 3 for fold  0 iter  1
time taken training 13.988102436065674
time taken predicting 0.3131239414215088
time taken predicting 1.0780785083770752
results  0.018997982515131136 mistakes in test 0.04371217215870881 for c 1.0 for d 3 for fold  1 iter  1
time taken training 13.636099815368652
time taken predicting 0.2782566547393799
time taken predicting 1.0950415134429932
result

time taken training 13.746039628982544
time taken predicting 0.353057861328125
time taken predicting 1.076659917831421
results  0.0010087424344317419 mistakes in test 0.02757229320780094 for c 1.0 for d 5 for fold  4 iter  1
--- %s seconds --- 4169.218121051788 time for d  5
time taken training 13.795139789581299
time taken predicting 0.29321932792663574
time taken predicting 1.0741593837738037
results  0.0 mistakes in test 0.03698722259583053 for c 0.001 for d 6 for fold  0 iter  1
time taken training 13.844605207443237
time taken predicting 0.3141591548919678
time taken predicting 1.1080443859100342
results  0.0008406186953597848 mistakes in test 0.02151983860121049 for c 0.001 for d 6 for fold  1 iter  1
time taken training 13.66275954246521
time taken predicting 0.2922203540802002
time taken predicting 1.067659854888916
results  0.00016812373907195696 mistakes in test 0.03362474781439139 for c 0.001 for d 6 for fold  2 iter  1
time taken training 13.494134426116943
time taken predi

results  0.053295225285810356 mistakes in test 0.05850706119704102 for c 0.001 for d 1 for fold  4 iter  2
time taken training 11.562323093414307
time taken predicting 0.3221435546875
time taken predicting 1.1085550785064697
results  0.02488231338264963 mistakes in test 0.05245460659045057 for c 0.01 for d 1 for fold  0 iter  2
time taken training 11.57045602798462
time taken predicting 0.3341102600097656
time taken predicting 1.2192859649658203
results  0.02706792199058507 mistakes in test 0.0484196368527236 for c 0.01 for d 1 for fold  1 iter  2
time taken training 11.41266393661499
time taken predicting 0.3151581287384033
time taken predicting 1.1100711822509766
results  0.03026227303295225 mistakes in test 0.05110961667787491 for c 0.01 for d 1 for fold  2 iter  2
time taken training 11.631086349487305
time taken predicting 0.3161928653717041
time taken predicting 1.1554408073425293
results  0.02639542703429724 mistakes in test 0.04371217215870881 for c 0.01 for d 1 for fold  3 ite

time taken predicting 0.29022717475891113
time taken predicting 1.158951997756958
results  0.0005043712172158709 mistakes in test 0.029589778076664425 for c 1.0 for d 3 for fold  0 iter  2
time taken training 14.241760015487671
time taken predicting 0.2872331142425537
time taken predicting 1.056248664855957
results  0.0005043712172158709 mistakes in test 0.023537323470073975 for c 1.0 for d 3 for fold  1 iter  2
time taken training 14.095239639282227
time taken predicting 0.3191823959350586
time taken predicting 1.087141990661621
results  0.0005043712172158709 mistakes in test 0.0242098184263618 for c 1.0 for d 3 for fold  2 iter  2
time taken training 13.872732877731323
time taken predicting 0.3121654987335205
time taken predicting 1.0941143035888672
results  0.00016812373907195696 mistakes in test 0.02488231338264963 for c 1.0 for d 3 for fold  3 iter  2
time taken training 13.682573556900024
time taken predicting 0.29524803161621094
time taken predicting 1.0920510292053223
results  

time taken training 13.54806661605835
time taken predicting 0.3002052307128906
time taken predicting 1.0830767154693604
results  0.0003362474781439139 mistakes in test 0.03227975790181574 for c 0.001 for d 6 for fold  1 iter  2
time taken training 13.49154543876648
time taken predicting 0.28989458084106445
time taken predicting 1.112541675567627
results  0.0003362474781439139 mistakes in test 0.0242098184263618 for c 0.001 for d 6 for fold  2 iter  2
time taken training 13.47190523147583
time taken predicting 0.30074000358581543
time taken predicting 1.1041743755340576
results  0.0 mistakes in test 0.02488231338264963 for c 0.001 for d 6 for fold  3 iter  2
time taken training 13.55314326286316
time taken predicting 0.3221397399902344
time taken predicting 1.105095624923706
results  0.0003362474781439139 mistakes in test 0.02824478816408877 for c 0.001 for d 6 for fold  4 iter  2
time taken training 13.75123643875122
time taken predicting 0.32909083366394043
time taken predicting 1.072

time taken training 11.44048523902893
time taken predicting 0.2982296943664551
time taken predicting 1.079120397567749
results  0.06540013449899126 mistakes in test 0.0941492938802959 for c 0.01 for d 1 for fold  2 iter  3
time taken training 11.553955316543579
time taken predicting 0.3390936851501465
time taken predicting 1.0831294059753418
results  0.030094149293880296 mistakes in test 0.04303967720242098 for c 0.01 for d 1 for fold  3 iter  3
time taken training 11.17107367515564
time taken predicting 0.33011770248413086
time taken predicting 1.0851004123687744
results  0.026899798251513115 mistakes in test 0.05110961667787491 for c 0.01 for d 1 for fold  4 iter  3
time taken training 12.136399745941162
time taken predicting 0.32709741592407227
time taken predicting 1.118969440460205
results  0.05094149293880296 mistakes in test 0.09145931405514458 for c 1.0 for d 1 for fold  0 iter  3
time taken training 12.13957691192627
time taken predicting 0.3471033573150635
time taken predicti

time taken training 13.791728258132935
time taken predicting 0.2951819896697998
time taken predicting 1.070110559463501
results  0.0006724949562878278 mistakes in test 0.020847343644922665 for c 1.0 for d 3 for fold  3 iter  3
time taken training 13.702962160110474
time taken predicting 0.28919172286987305
time taken predicting 1.1149883270263672
results  0.0006724949562878278 mistakes in test 0.02824478816408877 for c 1.0 for d 3 for fold  4 iter  3
--- %s seconds --- 7221.901741743088 time for d  3
time taken training 13.494843482971191
time taken predicting 0.28719449043273926
time taken predicting 1.0562660694122314
results  0.0003362474781439139 mistakes in test 0.02824478816408877 for c 0.001 for d 4 for fold  0 iter  3
time taken training 13.602426767349243
time taken predicting 0.2872040271759033
time taken predicting 1.0701360702514648
results  0.0005043712172158709 mistakes in test 0.02219233355749832 for c 0.001 for d 4 for fold  1 iter  3
time taken training 13.606347560882

results  0.00016812373907195696 mistakes in test 0.022864828513786146 for c 0.001 for d 6 for fold  3 iter  3
time taken training 13.377621412277222
time taken predicting 0.3361020088195801
time taken predicting 1.108060359954834
results  0.0003362474781439139 mistakes in test 0.03227975790181574 for c 0.001 for d 6 for fold  4 iter  3
time taken training 13.475456476211548
time taken predicting 0.2962369918823242
time taken predicting 1.078155279159546
results  0.0005043712172158709 mistakes in test 0.03026227303295225 for c 0.01 for d 6 for fold  0 iter  3
time taken training 13.487907409667969
time taken predicting 0.2951788902282715
time taken predicting 1.075122594833374
results  0.0 mistakes in test 0.026227303295225286 for c 0.01 for d 6 for fold  1 iter  3
time taken training 13.349421262741089
time taken predicting 0.2852041721343994
time taken predicting 1.0666868686676025
results  0.0 mistakes in test 0.02824478816408877 for c 0.01 for d 6 for fold  2 iter  3
time taken trai

time taken predicting 1.0731337070465088
results  0.028412911903160726 mistakes in test 0.03967720242098184 for c 0.01 for d 1 for fold  4 iter  4
time taken training 11.955124855041504
time taken predicting 0.3101768493652344
time taken predicting 1.150881052017212
results  0.027236045729657026 mistakes in test 0.07599193006052454 for c 1.0 for d 1 for fold  0 iter  4
time taken training 11.863898515701294
time taken predicting 0.30718421936035156
time taken predicting 1.0911097526550293
results  0.01714862138533961 mistakes in test 0.06724949562878278 for c 1.0 for d 1 for fold  1 iter  4
time taken training 12.043014287948608
time taken predicting 0.353057861328125
time taken predicting 1.1190578937530518
results  0.01832548755884331 mistakes in test 0.06186953597848016 for c 1.0 for d 1 for fold  2 iter  4
time taken training 12.11893630027771
time taken predicting 0.3321189880371094
time taken predicting 1.0895960330963135
results  0.02202420981842636 mistakes in test 0.0537995965

time taken training 13.835703134536743
time taken predicting 0.34108781814575195
time taken predicting 1.0572125911712646
results  0.0003362474781439139 mistakes in test 0.03160726294552791 for c 0.001 for d 4 for fold  0 iter  4
time taken training 13.996190309524536
time taken predicting 0.2951662540435791
time taken predicting 1.0985586643218994
results  0.0005043712172158709 mistakes in test 0.03362474781439139 for c 0.001 for d 4 for fold  1 iter  4
time taken training 13.740070343017578
time taken predicting 0.3021721839904785
time taken predicting 1.1005816459655762
results  0.0 mistakes in test 0.0242098184263618 for c 0.001 for d 4 for fold  2 iter  4
time taken training 13.627855062484741
time taken predicting 0.3031630516052246
time taken predicting 1.1011786460876465
results  0.0 mistakes in test 0.020174848688634835 for c 0.001 for d 4 for fold  3 iter  4
time taken training 13.789834976196289
time taken predicting 0.2922203540802002
time taken predicting 1.122053146362304

time taken training 13.349853754043579
time taken predicting 0.3151583671569824
time taken predicting 1.0706543922424316
results  0.0003362474781439139 mistakes in test 0.03564223268325487 for c 0.01 for d 6 for fold  1 iter  4
time taken training 13.480228662490845
time taken predicting 0.29069018363952637
time taken predicting 1.0912277698516846
results  0.00016812373907195696 mistakes in test 0.028917283120376596 for c 0.01 for d 6 for fold  2 iter  4
time taken training 13.269092321395874
time taken predicting 0.27327609062194824
time taken predicting 1.0561797618865967
results  0.0 mistakes in test 0.022864828513786146 for c 0.01 for d 6 for fold  3 iter  4
time taken training 13.271442890167236
time taken predicting 0.2872352600097656
time taken predicting 1.0887322425842285
results  0.00016812373907195696 mistakes in test 0.022864828513786146 for c 0.01 for d 6 for fold  4 iter  4
time taken training 13.415217876434326
time taken predicting 0.286226749420166
time taken predictin

time taken training 12.167553424835205
time taken predicting 0.32715392112731934
time taken predicting 1.0983467102050781
results  0.01866173503698722 mistakes in test 0.05043712172158709 for c 1.0 for d 1 for fold  2 iter  5
time taken training 11.774603605270386
time taken predicting 0.3261289596557617
time taken predicting 1.0928075313568115
results  0.017989240080699395 mistakes in test 0.06926698049764626 for c 1.0 for d 1 for fold  3 iter  5
time taken training 11.941099166870117
time taken predicting 0.31017279624938965
time taken predicting 1.1623501777648926
results  0.024546065904505716 mistakes in test 0.06455951580363148 for c 1.0 for d 1 for fold  4 iter  5
--- %s seconds --- 10295.384891033173 time for d  1
time taken training 11.867552757263184
time taken predicting 0.3061857223510742
time taken predicting 1.1105401515960693
results  0.0003362474781439139 mistakes in test 0.02488231338264963 for c 0.001 for d 2 for fold  0 iter  5
time taken training 11.834931135177612
t

results  0.0003362474781439139 mistakes in test 0.017484868863483525 for c 0.001 for d 4 for fold  2 iter  5
time taken training 13.61232328414917
time taken predicting 0.27823781967163086
time taken predicting 1.0521905422210693
results  0.042871553463349026 mistakes in test 0.06859448554135844 for c 0.001 for d 4 for fold  3 iter  5
time taken training 13.667470216751099
time taken predicting 0.299227237701416
time taken predicting 1.0685036182403564
results  0.00016812373907195696 mistakes in test 0.02824478816408877 for c 0.001 for d 4 for fold  4 iter  5
time taken training 13.66173243522644
time taken predicting 0.2891871929168701
time taken predicting 1.072131633758545
results  0.0003362474781439139 mistakes in test 0.01815736381977135 for c 0.01 for d 4 for fold  0 iter  5
time taken training 13.600966453552246
time taken predicting 0.2892303466796875
time taken predicting 1.1035645008087158
results  0.0003362474781439139 mistakes in test 0.025554808338937456 for c 0.01 for d 4

results  0.00016812373907195696 mistakes in test 0.03160726294552791 for c 0.01 for d 6 for fold  3 iter  5
time taken training 13.609658479690552
time taken predicting 0.28620243072509766
time taken predicting 1.1449451446533203
results  0.0 mistakes in test 0.029589778076664425 for c 0.01 for d 6 for fold  4 iter  5
time taken training 13.393890142440796
time taken predicting 0.3161299228668213
time taken predicting 1.115980863571167
results  0.0003362474781439139 mistakes in test 0.022864828513786146 for c 1.0 for d 6 for fold  0 iter  5
time taken training 13.294755220413208
time taken predicting 0.3116750717163086
time taken predicting 1.0551693439483643
results  0.0008406186953597848 mistakes in test 0.03564223268325487 for c 1.0 for d 6 for fold  1 iter  5
time taken training 13.561430931091309
time taken predicting 0.30014944076538086
time taken predicting 1.0452778339385986
results  0.0005043712172158709 mistakes in test 0.019502353732347006 for c 1.0 for d 6 for fold  2 iter 

time taken predicting 1.127507209777832
results  0.01933422999327505 mistakes in test 0.0531271015467384 for c 1.0 for d 1 for fold  4 iter  6
--- %s seconds --- 12076.238785505295 time for d  1
time taken training 12.010122776031494
time taken predicting 0.3390974998474121
time taken predicting 1.057723045349121
results  0.0006724949562878278 mistakes in test 0.0242098184263618 for c 0.001 for d 2 for fold  0 iter  6
time taken training 12.040956974029541
time taken predicting 0.2952146530151367
time taken predicting 1.0990912914276123
results  0.0016812373907195697 mistakes in test 0.03295225285810356 for c 0.001 for d 2 for fold  1 iter  6
time taken training 11.997248411178589
time taken predicting 0.30419158935546875
time taken predicting 1.080204725265503
results  0.003026227303295225 mistakes in test 0.03362474781439139 for c 0.001 for d 2 for fold  2 iter  6
time taken training 11.748552083969116
time taken predicting 0.31615662574768066
time taken predicting 1.1050751209259033

time taken predicting 0.28625965118408203
time taken predicting 1.0554563999176025
results  0.0005043712172158709 mistakes in test 0.016812373907195696 for c 0.01 for d 4 for fold  0 iter  6
time taken training 13.723803758621216
time taken predicting 0.29817938804626465
time taken predicting 1.0762016773223877
results  0.00016812373907195696 mistakes in test 0.03026227303295225 for c 0.01 for d 4 for fold  1 iter  6
time taken training 13.692917108535767
time taken predicting 0.2822551727294922
time taken predicting 1.0611329078674316
results  0.0005043712172158709 mistakes in test 0.026227303295225286 for c 0.01 for d 4 for fold  2 iter  6
time taken training 13.69790530204773
time taken predicting 0.2842683792114258
time taken predicting 1.0501646995544434
results  0.0 mistakes in test 0.025554808338937456 for c 0.01 for d 4 for fold  3 iter  6
time taken training 13.70089602470398
time taken predicting 0.28221678733825684
time taken predicting 1.0831341743469238
results  0.00033624

time taken predicting 0.2812175750732422
time taken predicting 1.1305677890777588
results  0.0003362474781439139 mistakes in test 0.03362474781439139 for c 1.0 for d 6 for fold  1 iter  6
time taken training 13.463772773742676
time taken predicting 0.2991790771484375
time taken predicting 1.036327600479126
results  0.00016812373907195696 mistakes in test 0.02824478816408877 for c 1.0 for d 6 for fold  2 iter  6
time taken training 13.38195276260376
time taken predicting 0.30814075469970703
time taken predicting 1.0552034378051758
results  0.0 mistakes in test 0.02757229320780094 for c 1.0 for d 6 for fold  3 iter  6
time taken training 13.669409275054932
time taken predicting 0.28293681144714355
time taken predicting 1.0586884021759033
results  0.00016812373907195696 mistakes in test 0.0242098184263618 for c 1.0 for d 6 for fold  4 iter  6
--- %s seconds --- 13379.65436410904 time for d  6
time taken training 13.470603704452515
time taken predicting 0.2842104434967041
time taken predic

time taken training 11.97838807106018
time taken predicting 0.2951829433441162
time taken predicting 1.076094627380371
results  0.0005043712172158709 mistakes in test 0.026227303295225286 for c 0.001 for d 2 for fold  2 iter  7
time taken training 11.718509674072266
time taken predicting 0.29920053482055664
time taken predicting 1.0920512676239014
results  0.0010087424344317419 mistakes in test 0.02824478816408877 for c 0.001 for d 2 for fold  3 iter  7
time taken training 11.825845718383789
time taken predicting 0.32712888717651367
time taken predicting 1.0790843963623047
results  0.0005043712172158709 mistakes in test 0.025554808338937456 for c 0.001 for d 2 for fold  4 iter  7
time taken training 11.818279504776001
time taken predicting 0.3082423210144043
time taken predicting 1.0924363136291504
results  0.0028581035642232682 mistakes in test 0.03496973772696705 for c 0.01 for d 2 for fold  0 iter  7
time taken training 11.562673568725586
time taken predicting 0.3037235736846924
tim

time taken training 13.919267892837524
time taken predicting 0.2802438735961914
time taken predicting 1.09647536277771
results  0.0016812373907195697 mistakes in test 0.026899798251513115 for c 0.01 for d 4 for fold  3 iter  7
time taken training 13.729321718215942
time taken predicting 0.31064414978027344
time taken predicting 1.0870661735534668
results  0.0003362474781439139 mistakes in test 0.020847343644922665 for c 0.01 for d 4 for fold  4 iter  7
time taken training 13.868506908416748
time taken predicting 0.3171842098236084
time taken predicting 1.0930347442626953
results  0.0003362474781439139 mistakes in test 0.023537323470073975 for c 1.0 for d 4 for fold  0 iter  7
time taken training 13.816573143005371
time taken predicting 0.30914974212646484
time taken predicting 1.0940589904785156
results  0.0 mistakes in test 0.02219233355749832 for c 1.0 for d 4 for fold  1 iter  7
time taken training 13.803111791610718
time taken predicting 0.2812187671661377
time taken predicting 1.0

time taken training 13.456457614898682
time taken predicting 0.29119205474853516
time taken predicting 1.0528454780578613
results  0.00016812373907195696 mistakes in test 0.029589778076664425 for c 1.0 for d 6 for fold  4 iter  7
--- %s seconds --- 15162.880019187927 time for d  6
time taken training 13.4314603805542
time taken predicting 0.3011612892150879
time taken predicting 1.0661606788635254
results  0.00016812373907195696 mistakes in test 0.02757229320780094 for c 0.001 for d 7 for fold  0 iter  7
time taken training 13.514523983001709
time taken predicting 0.29019784927368164
time taken predicting 1.0991051197052002
results  0.0 mistakes in test 0.03362474781439139 for c 0.001 for d 7 for fold  1 iter  7
time taken training 13.230107545852661
time taken predicting 0.2927408218383789
time taken predicting 1.090064525604248
results  0.0003362474781439139 mistakes in test 0.03227975790181574 for c 0.001 for d 7 for fold  2 iter  7
time taken training 13.440995693206787
time taken 

time taken predicting 0.33112096786499023
time taken predicting 1.1379139423370361
results  0.00016812373907195696 mistakes in test 0.03093476798924008 for c 0.001 for d 2 for fold  4 iter  8
time taken training 11.99399709701538
time taken predicting 0.3121929168701172
time taken predicting 1.1355924606323242
results  0.0003362474781439139 mistakes in test 0.03160726294552791 for c 0.01 for d 2 for fold  0 iter  8
time taken training 11.793058633804321
time taken predicting 0.30817651748657227
time taken predicting 1.070143461227417
results  0.0011768661735036988 mistakes in test 0.025554808338937456 for c 0.01 for d 2 for fold  1 iter  8
time taken training 12.091672897338867
time taken predicting 0.3081817626953125
time taken predicting 1.0691871643066406
results  0.0006724949562878278 mistakes in test 0.03698722259583053 for c 0.01 for d 2 for fold  2 iter  8
time taken training 12.12001657485962
time taken predicting 0.29720306396484375
time taken predicting 1.030221939086914
resu

time taken training 13.649214267730713
time taken predicting 0.27722668647766113
time taken predicting 1.047175407409668
results  0.0 mistakes in test 0.026227303295225286 for c 1.0 for d 4 for fold  0 iter  8
time taken training 13.918736219406128
time taken predicting 0.2908306121826172
time taken predicting 1.0360190868377686
results  0.0015131136516476126 mistakes in test 0.01882985877605918 for c 1.0 for d 4 for fold  1 iter  8
time taken training 14.011870622634888
time taken predicting 0.33507442474365234
time taken predicting 1.107576608657837
results  0.0003362474781439139 mistakes in test 0.03160726294552791 for c 1.0 for d 4 for fold  2 iter  8
time taken training 13.861608028411865
time taken predicting 0.3101370334625244
time taken predicting 1.0881452560424805
results  0.0006724949562878278 mistakes in test 0.019502353732347006 for c 1.0 for d 4 for fold  3 iter  8
time taken training 13.933838844299316
time taken predicting 0.30416059494018555
time taken predicting 1.075

results  0.0 mistakes in test 0.03900470746469401 for c 0.001 for d 7 for fold  0 iter  8
time taken training 13.438095331192017
time taken predicting 0.31817173957824707
time taken predicting 1.0519156455993652
results  0.00016812373907195696 mistakes in test 0.028917283120376596 for c 0.001 for d 7 for fold  1 iter  8
time taken training 13.760438680648804
time taken predicting 0.30216026306152344
time taken predicting 1.0516345500946045
results  0.0005043712172158709 mistakes in test 0.03295225285810356 for c 0.001 for d 7 for fold  2 iter  8
time taken training 13.775506496429443
time taken predicting 0.3031489849090576
time taken predicting 1.0701642036437988
results  0.00016812373907195696 mistakes in test 0.03093476798924008 for c 0.001 for d 7 for fold  3 iter  8
time taken training 13.439160108566284
time taken predicting 0.29416537284851074
time taken predicting 1.0741350650787354
results  0.00016812373907195696 mistakes in test 0.03093476798924008 for c 0.001 for d 7 for fol

time taken predicting 0.33606457710266113
time taken predicting 1.0451793670654297
results  0.0006724949562878278 mistakes in test 0.028917283120376596 for c 0.01 for d 2 for fold  1 iter  9
time taken training 11.686201333999634
time taken predicting 0.29222702980041504
time taken predicting 1.041224718093872
results  0.0006724949562878278 mistakes in test 0.03429724277067922 for c 0.01 for d 2 for fold  2 iter  9
time taken training 11.908096075057983
time taken predicting 0.2922806739807129
time taken predicting 1.074134349822998
results  0.0005043712172158709 mistakes in test 0.03160726294552791 for c 0.01 for d 2 for fold  3 iter  9
time taken training 12.058096170425415
time taken predicting 0.30521130561828613
time taken predicting 1.0701699256896973
results  0.0006724949562878278 mistakes in test 0.028917283120376596 for c 0.01 for d 2 for fold  4 iter  9
time taken training 11.91659665107727
time taken predicting 0.35106348991394043
time taken predicting 1.0378198623657227
res

time taken training 13.872812032699585
time taken predicting 0.29317212104797363
time taken predicting 1.0309700965881348
results  0.00016812373907195696 mistakes in test 0.02824478816408877 for c 1.0 for d 4 for fold  2 iter  9
time taken training 13.55219554901123
time taken predicting 0.2682504653930664
time taken predicting 1.075972557067871
results  0.00016812373907195696 mistakes in test 0.022864828513786146 for c 1.0 for d 4 for fold  3 iter  9
time taken training 13.672067880630493
time taken predicting 0.3027305603027344
time taken predicting 1.0860991477966309
results  0.0005043712172158709 mistakes in test 0.023537323470073975 for c 1.0 for d 4 for fold  4 iter  9
--- %s seconds --- 18201.004148483276 time for d  4
time taken training 13.719877481460571
time taken predicting 0.28922295570373535
time taken predicting 1.0380070209503174
results  0.0015131136516476126 mistakes in test 0.025554808338937456 for c 0.001 for d 5 for fold  0 iter  9
time taken training 13.7461488246

results  0.0 mistakes in test 0.03698722259583053 for c 0.001 for d 7 for fold  2 iter  9
time taken training 13.338932991027832
time taken predicting 0.2852499485015869
time taken predicting 1.0781939029693604
results  0.00016812373907195696 mistakes in test 0.029589778076664425 for c 0.001 for d 7 for fold  3 iter  9
time taken training 13.488994121551514
time taken predicting 0.2792212963104248
time taken predicting 1.0891385078430176
results  0.00016812373907195696 mistakes in test 0.03295225285810356 for c 0.001 for d 7 for fold  4 iter  9
time taken training 13.346379280090332
time taken predicting 0.2961852550506592
time taken predicting 1.0601966381072998
results  0.00016812373907195696 mistakes in test 0.029589778076664425 for c 0.01 for d 7 for fold  0 iter  9
time taken training 13.534573554992676
time taken predicting 0.2921879291534424
time taken predicting 1.1162004470825195
results  0.00016812373907195696 mistakes in test 0.03295225285810356 for c 0.01 for d 7 for fold  

time taken training 11.933625221252441
time taken predicting 0.3091764450073242
time taken predicting 1.097036361694336
results  0.0003362474781439139 mistakes in test 0.03429724277067922 for c 0.01 for d 2 for fold  3 iter  10
time taken training 12.293480157852173
time taken predicting 0.3001728057861328
time taken predicting 1.1105542182922363
results  0.0010087424344317419 mistakes in test 0.029589778076664425 for c 0.01 for d 2 for fold  4 iter  10
time taken training 12.210313320159912
time taken predicting 0.2842409610748291
time taken predicting 1.0970721244812012
results  0.0006724949562878278 mistakes in test 0.02757229320780094 for c 1.0 for d 2 for fold  0 iter  10
time taken training 11.881102085113525
time taken predicting 0.3091757297515869
time taken predicting 1.0957636833190918
results  0.0015131136516476126 mistakes in test 0.029589778076664425 for c 1.0 for d 2 for fold  1 iter  10
time taken training 12.13982105255127
time taken predicting 0.3092033863067627
time t

time taken training 13.908807516098022
time taken predicting 0.295215368270874
time taken predicting 1.0781211853027344
results  0.0005043712172158709 mistakes in test 0.02757229320780094 for c 1.0 for d 4 for fold  4 iter  10
--- %s seconds --- 19985.276280641556 time for d  4
time taken training 13.757439136505127
time taken predicting 0.30514025688171387
time taken predicting 1.0970592498779297
results  0.00016812373907195696 mistakes in test 0.01882985877605918 for c 0.001 for d 5 for fold  0 iter  10
time taken training 13.88376522064209
time taken predicting 0.3141615390777588
time taken predicting 1.082066297531128
results  0.0003362474781439139 mistakes in test 0.020847343644922665 for c 0.001 for d 5 for fold  1 iter  10
time taken training 13.595650434494019
time taken predicting 0.292222261428833
time taken predicting 1.0830979347229004
results  0.00016812373907195696 mistakes in test 0.017484868863483525 for c 0.001 for d 5 for fold  2 iter  10
time taken training 13.585587

results  0.0003362474781439139 mistakes in test 0.03564223268325487 for c 0.001 for d 7 for fold  4 iter  10
time taken training 13.45566177368164
time taken predicting 0.2812011241912842
time taken predicting 1.0951392650604248
results  0.0003362474781439139 mistakes in test 0.02824478816408877 for c 0.01 for d 7 for fold  0 iter  10
time taken training 13.283959150314331
time taken predicting 0.2672548294067383
time taken predicting 1.1040537357330322
results  0.00016812373907195696 mistakes in test 0.025554808338937456 for c 0.01 for d 7 for fold  1 iter  10
time taken training 13.384003162384033
time taken predicting 0.27723073959350586
time taken predicting 1.0323216915130615
results  0.0 mistakes in test 0.026899798251513115 for c 0.01 for d 7 for fold  2 iter  10
time taken training 13.535873413085938
time taken predicting 0.2847592830657959
time taken predicting 1.056225061416626
results  0.00016812373907195696 mistakes in test 0.0363147276395427 for c 0.01 for d 7 for fold  3 

time taken training 11.75996994972229
time taken predicting 0.3052511215209961
time taken predicting 1.039215326309204
results  0.0016812373907195697 mistakes in test 0.028917283120376596 for c 1.0 for d 2 for fold  0 iter  11
time taken training 11.57516860961914
time taken predicting 0.2862095832824707
time taken predicting 1.0467419624328613
results  0.0011768661735036988 mistakes in test 0.03564223268325487 for c 1.0 for d 2 for fold  1 iter  11
time taken training 11.749463081359863
time taken predicting 0.28626346588134766
time taken predicting 1.0716485977172852
results  0.00016812373907195696 mistakes in test 0.02219233355749832 for c 1.0 for d 2 for fold  2 iter  11
time taken training 11.690484762191772
time taken predicting 0.3171529769897461
time taken predicting 1.0752458572387695
results  0.0008406186953597848 mistakes in test 0.026227303295225286 for c 1.0 for d 2 for fold  3 iter  11
time taken training 12.01711916923523
time taken predicting 0.302156925201416
time take

time taken predicting 1.0401904582977295
results  0.0003362474781439139 mistakes in test 0.0242098184263618 for c 0.001 for d 5 for fold  0 iter  11
time taken training 13.52054500579834
time taken predicting 0.28623104095458984
time taken predicting 0.9953479766845703
results  0.0003362474781439139 mistakes in test 0.03160726294552791 for c 0.001 for d 5 for fold  1 iter  11
time taken training 13.496325254440308
time taken predicting 0.3001878261566162
time taken predicting 1.1321756839752197
results  0.00016812373907195696 mistakes in test 0.023537323470073975 for c 0.001 for d 5 for fold  2 iter  11
time taken training 13.235977172851562
time taken predicting 0.3022737503051758
time taken predicting 1.0612123012542725
results  0.0003362474781439139 mistakes in test 0.02151983860121049 for c 0.001 for d 5 for fold  3 iter  11
time taken training 13.585785627365112
time taken predicting 0.278780460357666
time taken predicting 1.0431716442108154
results  0.0003362474781439139 mistakes

time taken training 13.643532276153564
time taken predicting 0.28221940994262695
time taken predicting 1.1090021133422852
results  0.00016812373907195696 mistakes in test 0.0410221923335575 for c 0.01 for d 7 for fold  1 iter  11
time taken training 13.50247597694397
time taken predicting 0.28819751739501953
time taken predicting 1.092116355895996
results  0.0 mistakes in test 0.026227303295225286 for c 0.01 for d 7 for fold  2 iter  11
time taken training 13.46488356590271
time taken predicting 0.3290886878967285
time taken predicting 1.0601372718811035
results  0.0003362474781439139 mistakes in test 0.0242098184263618 for c 0.01 for d 7 for fold  3 iter  11
time taken training 13.464460134506226
time taken predicting 0.30215954780578613
time taken predicting 1.0329086780548096
results  0.00016812373907195696 mistakes in test 0.03564223268325487 for c 0.01 for d 7 for fold  4 iter  11
time taken training 13.318521499633789
time taken predicting 0.301159143447876
time taken predicting 

results  0.0010087424344317419 mistakes in test 0.026899798251513115 for c 1.0 for d 2 for fold  1 iter  12
time taken training 11.998516082763672
time taken predicting 0.31511640548706055
time taken predicting 1.0971286296844482
results  0.0008406186953597848 mistakes in test 0.026227303295225286 for c 1.0 for d 2 for fold  2 iter  12
time taken training 12.021251201629639
time taken predicting 0.30518341064453125
time taken predicting 1.0521633625030518
results  0.00823806321452589 mistakes in test 0.03698722259583053 for c 1.0 for d 2 for fold  3 iter  12
time taken training 12.06834888458252
time taken predicting 0.3251049518585205
time taken predicting 1.0811409950256348
results  0.0008406186953597848 mistakes in test 0.03026227303295225 for c 1.0 for d 2 for fold  4 iter  12
--- %s seconds --- 23000.16704082489 time for d  2
time taken training 14.402034282684326
time taken predicting 0.3101658821105957
time taken predicting 1.0716452598571777
results  0.0005043712172158709 mista

time taken training 13.824785470962524
time taken predicting 0.2877366542816162
time taken predicting 1.0332787036895752
results  0.00016812373907195696 mistakes in test 0.020847343644922665 for c 0.001 for d 5 for fold  2 iter  12
time taken training 13.974101066589355
time taken predicting 0.32010555267333984
time taken predicting 1.0621790885925293
results  0.00016812373907195696 mistakes in test 0.022864828513786146 for c 0.001 for d 5 for fold  3 iter  12
time taken training 13.637950420379639
time taken predicting 0.3041541576385498
time taken predicting 1.0661051273345947
results  0.0003362474781439139 mistakes in test 0.025554808338937456 for c 0.001 for d 5 for fold  4 iter  12
time taken training 13.535571575164795
time taken predicting 0.28620362281799316
time taken predicting 1.0252277851104736
results  0.00016812373907195696 mistakes in test 0.02757229320780094 for c 0.01 for d 5 for fold  0 iter  12
time taken training 13.600833654403687
time taken predicting 0.3068685531

time taken training 13.535563945770264
time taken predicting 0.3091435432434082
time taken predicting 1.056861162185669
results  0.0 mistakes in test 0.02757229320780094 for c 0.01 for d 7 for fold  3 iter  12
time taken training 13.461223363876343
time taken predicting 0.29421424865722656
time taken predicting 1.0538554191589355
results  0.00016812373907195696 mistakes in test 0.03026227303295225 for c 0.01 for d 7 for fold  4 iter  12
time taken training 13.354092121124268
time taken predicting 0.2931864261627197
time taken predicting 1.080124855041504
results  0.00016812373907195696 mistakes in test 0.03496973772696705 for c 1.0 for d 7 for fold  0 iter  12
time taken training 13.300537824630737
time taken predicting 0.32209062576293945
time taken predicting 1.0711932182312012
results  0.00016812373907195696 mistakes in test 0.03362474781439139 for c 1.0 for d 7 for fold  1 iter  12
time taken training 13.3073410987854
time taken predicting 0.28580737113952637
time taken predicting 

time taken predicting 1.0592434406280518
results  0.0020174848688634837 mistakes in test 0.03564223268325487 for c 1.0 for d 2 for fold  3 iter  13
time taken training 11.890700101852417
time taken predicting 0.28823137283325195
time taken predicting 1.0332152843475342
results  0.0003362474781439139 mistakes in test 0.022864828513786146 for c 1.0 for d 2 for fold  4 iter  13
--- %s seconds --- 24779.944413900375 time for d  2
time taken training 13.748081684112549
time taken predicting 0.28027844429016113
time taken predicting 1.0282540321350098
results  0.0003362474781439139 mistakes in test 0.0242098184263618 for c 0.001 for d 3 for fold  0 iter  13
time taken training 13.973257303237915
time taken predicting 0.2852334976196289
time taken predicting 1.0163674354553223
results  0.00016812373907195696 mistakes in test 0.02488231338264963 for c 0.001 for d 3 for fold  1 iter  13
time taken training 14.081469774246216
time taken predicting 0.28124260902404785
time taken predicting 1.0367

time taken training 13.549482107162476
time taken predicting 0.261599063873291
time taken predicting 1.0431654453277588
results  0.0005043712172158709 mistakes in test 0.020847343644922665 for c 0.001 for d 5 for fold  4 iter  13
time taken training 13.596359729766846
time taken predicting 0.30514955520629883
time taken predicting 1.1116461753845215
results  0.0003362474781439139 mistakes in test 0.026899798251513115 for c 0.01 for d 5 for fold  0 iter  13
time taken training 13.377053022384644
time taken predicting 0.2742493152618408
time taken predicting 1.0369935035705566
results  0.0 mistakes in test 0.026227303295225286 for c 0.01 for d 5 for fold  1 iter  13
time taken training 13.580112218856812
time taken predicting 0.30022501945495605
time taken predicting 1.0218043327331543
results  0.0003362474781439139 mistakes in test 0.022864828513786146 for c 0.01 for d 5 for fold  2 iter  13
time taken training 13.636685132980347
time taken predicting 0.26230311393737793
time taken pred

time taken training 12.81591010093689
time taken predicting 0.28523898124694824
time taken predicting 1.001326084136963
results  0.00016812373907195696 mistakes in test 0.03227975790181574 for c 1.0 for d 7 for fold  0 iter  13
time taken training 12.982909917831421
time taken predicting 0.2603037357330322
time taken predicting 0.9753942489624023
results  0.0 mistakes in test 0.03496973772696705 for c 1.0 for d 7 for fold  1 iter  13
time taken training 12.897719621658325
time taken predicting 0.27223896980285645
time taken predicting 1.0133347511291504
results  0.00016812373907195696 mistakes in test 0.028917283120376596 for c 1.0 for d 7 for fold  2 iter  13
time taken training 12.68464994430542
time taken predicting 0.2672841548919678
time taken predicting 1.0294246673583984
results  0.00016812373907195696 mistakes in test 0.03833221250840619 for c 1.0 for d 7 for fold  3 iter  13
time taken training 13.001798868179321
time taken predicting 0.26428890228271484
time taken predicting 

time taken predicting 1.0150165557861328
results  0.0005043712172158709 mistakes in test 0.03160726294552791 for c 0.001 for d 3 for fold  0 iter  14
time taken training 13.29292368888855
time taken predicting 0.2921895980834961
time taken predicting 1.064697265625
results  0.0021856086079354406 mistakes in test 0.03227975790181574 for c 0.001 for d 3 for fold  1 iter  14
time taken training 13.271091222763062
time taken predicting 0.25830531120300293
time taken predicting 0.9804091453552246
results  0.0003362474781439139 mistakes in test 0.01882985877605918 for c 0.001 for d 3 for fold  2 iter  14
time taken training 13.259859323501587
time taken predicting 0.26924848556518555
time taken predicting 1.0033154487609863
results  0.00016812373907195696 mistakes in test 0.020847343644922665 for c 0.001 for d 3 for fold  3 iter  14
time taken training 13.42048454284668
time taken predicting 0.2981607913970947
time taken predicting 0.9883606433868408
results  0.0003362474781439139 mistakes i

time taken training 12.979068279266357
time taken predicting 0.2702784538269043
time taken predicting 1.0024073123931885
results  0.00016812373907195696 mistakes in test 0.03160726294552791 for c 0.01 for d 5 for fold  1 iter  14
time taken training 12.929277896881104
time taken predicting 0.2629892826080322
time taken predicting 1.0721371173858643
results  0.0003362474781439139 mistakes in test 0.01882985877605918 for c 0.01 for d 5 for fold  2 iter  14
time taken training 12.922873973846436
time taken predicting 0.28620052337646484
time taken predicting 1.0123238563537598
results  0.0003362474781439139 mistakes in test 0.02151983860121049 for c 0.01 for d 5 for fold  3 iter  14
time taken training 13.059179782867432
time taken predicting 0.2647554874420166
time taken predicting 0.9654185771942139
results  0.0003362474781439139 mistakes in test 0.020847343644922665 for c 0.01 for d 5 for fold  4 iter  14
time taken training 13.058069705963135
time taken predicting 0.30019354820251465


results  0.00016812373907195696 mistakes in test 0.04034969737726967 for c 1.0 for d 7 for fold  1 iter  14
time taken training 13.11817741394043
time taken predicting 0.2592763900756836
time taken predicting 1.006314754486084
results  0.0003362474781439139 mistakes in test 0.03026227303295225 for c 1.0 for d 7 for fold  2 iter  14
time taken training 12.913836479187012
time taken predicting 0.295212984085083
time taken predicting 1.0243258476257324
results  0.01160053799596503 mistakes in test 0.03765971755211836 for c 1.0 for d 7 for fold  3 iter  14
time taken training 12.936930179595947
time taken predicting 0.2812480926513672
time taken predicting 0.9633238315582275
results  0.0003362474781439139 mistakes in test 0.022864828513786146 for c 1.0 for d 7 for fold  4 iter  14
--- %s seconds --- 27808.36766076088 time for d  7
--- %s seconds --- 1707.9378373622894 time for iter  14
time taken training 10.068400144577026
time taken predicting 0.28025245666503906
time taken predicting 1.

time taken training 13.206841468811035
time taken predicting 0.2702634334564209
time taken predicting 0.980381965637207
results  0.003698722259583053 mistakes in test 0.029589778076664425 for c 0.001 for d 3 for fold  2 iter  15
time taken training 13.543415784835815
time taken predicting 0.2595071792602539
time taken predicting 0.9723715782165527
results  0.0003362474781439139 mistakes in test 0.03093476798924008 for c 0.001 for d 3 for fold  3 iter  15
time taken training 13.251611232757568
time taken predicting 0.27430057525634766
time taken predicting 1.0040316581726074
results  0.0 mistakes in test 0.014794889038332213 for c 0.001 for d 3 for fold  4 iter  15
time taken training 13.183403491973877
time taken predicting 0.26227450370788574
time taken predicting 1.0302486419677734
results  0.0015131136516476126 mistakes in test 0.0242098184263618 for c 0.01 for d 3 for fold  0 iter  15
time taken training 12.940244436264038
time taken predicting 0.2782557010650635
time taken predict

time taken training 13.179768800735474
time taken predicting 0.2882270812988281
time taken predicting 1.0282158851623535
results  0.00016812373907195696 mistakes in test 0.03160726294552791 for c 0.01 for d 5 for fold  3 iter  15
time taken training 13.161561965942383
time taken predicting 0.2682523727416992
time taken predicting 1.0092711448669434
results  0.0 mistakes in test 0.01815736381977135 for c 0.01 for d 5 for fold  4 iter  15
time taken training 12.968377590179443
time taken predicting 0.26426053047180176
time taken predicting 0.9923455715179443
results  0.0003362474781439139 mistakes in test 0.01815736381977135 for c 1.0 for d 5 for fold  0 iter  15
time taken training 13.10538649559021
time taken predicting 0.2672615051269531
time taken predicting 1.0347974300384521
results  0.00016812373907195696 mistakes in test 0.03362474781439139 for c 1.0 for d 5 for fold  1 iter  15
time taken training 12.896463871002197
time taken predicting 0.27525854110717773
time taken predicting

time taken training 12.883061170578003
time taken predicting 0.31728219985961914
time taken predicting 0.9833755493164062
results  0.00016812373907195696 mistakes in test 0.02151983860121049 for c 1.0 for d 7 for fold  4 iter  15
--- %s seconds --- 29513.105744838715 time for d  7
--- %s seconds --- 1704.7123560905457 time for iter  15
time taken training 10.313148736953735
time taken predicting 0.28720617294311523
time taken predicting 1.0716145038604736
results  0.05480833893745797 mistakes in test 0.04438466711499664 for c 0.001 for d 1 for fold  0 iter  16
time taken training 9.995890617370605
time taken predicting 0.2941875457763672
time taken predicting 0.9813735485076904
results  0.052286482851378616 mistakes in test 0.07330195023537324 for c 0.001 for d 1 for fold  1 iter  16
time taken training 10.060165882110596
time taken predicting 0.2942171096801758
time taken predicting 0.9814155101776123
results  0.05346334902488231 mistakes in test 0.05648957632817754 for c 0.001 for d 

time taken training 13.515015602111816
time taken predicting 0.2603111267089844
time taken predicting 0.9786531925201416
results  0.0005043712172158709 mistakes in test 0.02757229320780094 for c 0.001 for d 3 for fold  4 iter  16
time taken training 13.353262424468994
time taken predicting 0.29222846031188965
time taken predicting 0.9972982406616211
results  0.0006724949562878278 mistakes in test 0.02151983860121049 for c 0.01 for d 3 for fold  0 iter  16
time taken training 13.588896751403809
time taken predicting 0.27424049377441406
time taken predicting 1.0357348918914795
results  0.0008406186953597848 mistakes in test 0.03160726294552791 for c 0.01 for d 3 for fold  1 iter  16
time taken training 13.498768091201782
time taken predicting 0.297177791595459
time taken predicting 1.0075361728668213
results  0.0003362474781439139 mistakes in test 0.0242098184263618 for c 0.01 for d 3 for fold  2 iter  16
time taken training 13.522645711898804
time taken predicting 0.2902219295501709
tim

time taken training 12.941766500473022
time taken predicting 0.302156925201416
time taken predicting 1.0293164253234863
results  0.00016812373907195696 mistakes in test 0.020847343644922665 for c 1.0 for d 5 for fold  0 iter  16
time taken training 13.079537868499756
time taken predicting 0.26828527450561523
time taken predicting 1.041722059249878
results  0.0003362474781439139 mistakes in test 0.03227975790181574 for c 1.0 for d 5 for fold  1 iter  16
time taken training 13.013514757156372
time taken predicting 0.30173420906066895
time taken predicting 1.013261318206787
results  0.0 mistakes in test 0.02488231338264963 for c 1.0 for d 5 for fold  2 iter  16
time taken training 13.160261869430542
time taken predicting 0.3171985149383545
time taken predicting 0.9733729362487793
results  0.0006724949562878278 mistakes in test 0.0242098184263618 for c 1.0 for d 5 for fold  3 iter  16
time taken training 13.062198638916016
time taken predicting 0.30219459533691406
time taken predicting 0.9

time taken predicting 1.0103001594543457
results  0.054640215198386015 mistakes in test 0.0652320107599193 for c 0.001 for d 1 for fold  0 iter  17
time taken training 9.925947189331055
time taken predicting 0.28574585914611816
time taken predicting 0.9714193344116211
results  0.0531271015467384 mistakes in test 0.05716207128446537 for c 0.001 for d 1 for fold  1 iter  17
time taken training 9.96109390258789
time taken predicting 0.2852444648742676
time taken predicting 0.9903225898742676
results  0.0554808338937458 mistakes in test 0.05178211163416274 for c 0.001 for d 1 for fold  2 iter  17
time taken training 9.932626008987427
time taken predicting 0.28324460983276367
time taken predicting 1.0033154487609863
results  0.05346334902488231 mistakes in test 0.06657700067249496 for c 0.001 for d 1 for fold  3 iter  17
time taken training 9.903691291809082
time taken predicting 0.2812614440917969
time taken predicting 0.9639382362365723
results  0.052958977807666445 mistakes in test 0.065

time taken training 13.691481113433838
time taken predicting 0.28226613998413086
time taken predicting 1.013288974761963
results  0.00605245460659045 mistakes in test 0.028917283120376596 for c 0.01 for d 3 for fold  1 iter  17
time taken training 13.591755151748657
time taken predicting 0.28918933868408203
time taken predicting 0.999305009841919
results  0.0005043712172158709 mistakes in test 0.02151983860121049 for c 0.01 for d 3 for fold  2 iter  17
time taken training 13.448531866073608
time taken predicting 0.28420400619506836
time taken predicting 1.0133709907531738
results  0.0011768661735036988 mistakes in test 0.03093476798924008 for c 0.01 for d 3 for fold  3 iter  17
time taken training 13.578994035720825
time taken predicting 0.2623271942138672
time taken predicting 0.9624240398406982
results  0.00016812373907195696 mistakes in test 0.023537323470073975 for c 0.01 for d 3 for fold  4 iter  17
time taken training 13.467276334762573
time taken predicting 0.29618024826049805
t

time taken training 13.039512157440186
time taken predicting 0.2732429504394531
time taken predicting 0.997337818145752
results  0.0003362474781439139 mistakes in test 0.023537323470073975 for c 1.0 for d 5 for fold  2 iter  17
time taken training 13.00194525718689
time taken predicting 0.25930261611938477
time taken predicting 0.9903914928436279
results  0.00016812373907195696 mistakes in test 0.03026227303295225 for c 1.0 for d 5 for fold  3 iter  17
time taken training 13.070909023284912
time taken predicting 0.281787633895874
time taken predicting 0.9945156574249268
results  0.0 mistakes in test 0.0242098184263618 for c 1.0 for d 5 for fold  4 iter  17
--- %s seconds --- 32429.442744255066 time for d  5
time taken training 12.917619228363037
time taken predicting 0.27223730087280273
time taken predicting 1.0063135623931885
results  0.0003362474781439139 mistakes in test 0.025554808338937456 for c 0.001 for d 6 for fold  0 iter  17
time taken training 13.126904010772705
time taken p

time taken predicting 1.0097990036010742
results  0.05783456624075319 mistakes in test 0.06321452589105582 for c 0.001 for d 1 for fold  2 iter  18
time taken training 9.910040378570557
time taken predicting 0.3121683597564697
time taken predicting 0.9624125957489014
results  0.05262273032952253 mistakes in test 0.05581708137188971 for c 0.001 for d 1 for fold  3 iter  18
time taken training 10.310310125350952
time taken predicting 0.2912251949310303
time taken predicting 1.0167617797851562
results  0.05262273032952253 mistakes in test 0.05447209145931405 for c 0.001 for d 1 for fold  4 iter  18
time taken training 10.831352710723877
time taken predicting 0.27230191230773926
time taken predicting 0.979377031326294
results  0.029589778076664425 mistakes in test 0.04640215198386012 for c 0.01 for d 1 for fold  0 iter  18
time taken training 10.942233324050903
time taken predicting 0.29817914962768555
time taken predicting 1.0930800437927246
results  0.025722932078009415 mistakes in test 

time taken training 13.42879343032837
time taken predicting 0.27326464653015137
time taken predicting 1.0162794589996338
results  0.0008406186953597848 mistakes in test 0.023537323470073975 for c 0.01 for d 3 for fold  3 iter  18
time taken training 13.471428155899048
time taken predicting 0.27821969985961914
time taken predicting 1.0235838890075684
results  0.0006724949562878278 mistakes in test 0.025554808338937456 for c 0.01 for d 3 for fold  4 iter  18
time taken training 13.464576244354248
time taken predicting 0.290205717086792
time taken predicting 0.9983077049255371
results  0.0003362474781439139 mistakes in test 0.026227303295225286 for c 1.0 for d 3 for fold  0 iter  18
time taken training 13.629791259765625
time taken predicting 0.2652881145477295
time taken predicting 1.0250043869018555
results  0.0003362474781439139 mistakes in test 0.026227303295225286 for c 1.0 for d 3 for fold  1 iter  18
time taken training 13.406341314315796
time taken predicting 0.28221964836120605
t

time taken training 13.17708444595337
time taken predicting 0.2712419033050537
time taken predicting 0.9930522441864014
results  0.00016812373907195696 mistakes in test 0.020174848688634835 for c 1.0 for d 5 for fold  4 iter  18
--- %s seconds --- 34148.15694856644 time for d  5
time taken training 12.980486392974854
time taken predicting 0.2981710433959961
time taken predicting 1.0042777061462402
results  0.0 mistakes in test 0.03160726294552791 for c 0.001 for d 6 for fold  0 iter  18
time taken training 13.027069091796875
time taken predicting 0.2629852294921875
time taken predicting 1.0783452987670898
results  0.0003362474781439139 mistakes in test 0.029589778076664425 for c 0.001 for d 6 for fold  1 iter  18
time taken training 13.104018449783325
time taken predicting 0.2682528495788574
time taken predicting 1.0103018283843994
results  0.00016812373907195696 mistakes in test 0.02488231338264963 for c 0.001 for d 6 for fold  2 iter  18
time taken training 13.08192753791809
time tak

time taken predicting 1.029252529144287
results  0.05262273032952253 mistakes in test 0.06254203093476798 for c 0.001 for d 1 for fold  4 iter  19
time taken training 10.745651483535767
time taken predicting 0.26624250411987305
time taken predicting 1.0262932777404785
results  0.030094149293880296 mistakes in test 0.04909213180901143 for c 0.01 for d 1 for fold  0 iter  19
time taken training 10.837754011154175
time taken predicting 0.277346134185791
time taken predicting 1.013251781463623
results  0.03026227303295225 mistakes in test 0.05110961667787491 for c 0.01 for d 1 for fold  1 iter  19
time taken training 11.03667664527893
time taken predicting 0.29620790481567383
time taken predicting 0.9746019840240479
results  0.026731674512441156 mistakes in test 0.04371217215870881 for c 0.01 for d 1 for fold  2 iter  19
time taken training 10.687830924987793
time taken predicting 0.29222726821899414
time taken predicting 1.015984058380127
results  0.030766644250168125 mistakes in test 0.0

time taken training 13.18009352684021
time taken predicting 0.3001680374145508
time taken predicting 0.9594368934631348
results  0.0 mistakes in test 0.02151983860121049 for c 1.0 for d 3 for fold  0 iter  19
time taken training 13.459378004074097
time taken predicting 0.28321123123168945
time taken predicting 0.9804825782775879
results  0.00016812373907195696 mistakes in test 0.02488231338264963 for c 1.0 for d 3 for fold  1 iter  19
time taken training 13.340631008148193
time taken predicting 0.2852439880371094
time taken predicting 0.9756224155426025
results  0.00016812373907195696 mistakes in test 0.025554808338937456 for c 1.0 for d 3 for fold  2 iter  19
time taken training 13.336869955062866
time taken predicting 0.2952120304107666
time taken predicting 0.9784257411956787
results  0.0003362474781439139 mistakes in test 0.01882985877605918 for c 1.0 for d 3 for fold  3 iter  19
time taken training 13.474771499633789
time taken predicting 0.266324520111084
time taken predicting 0.

results  0.0 mistakes in test 0.02824478816408877 for c 0.001 for d 6 for fold  0 iter  19
time taken training 12.949446201324463
time taken predicting 0.2872002124786377
time taken predicting 1.027256965637207
results  0.0003362474781439139 mistakes in test 0.0242098184263618 for c 0.001 for d 6 for fold  1 iter  19
time taken training 13.074267625808716
time taken predicting 0.3031888008117676
time taken predicting 0.9843757152557373
results  0.00016812373907195696 mistakes in test 0.03026227303295225 for c 0.001 for d 6 for fold  2 iter  19
time taken training 13.049330472946167
time taken predicting 0.27224135398864746
time taken predicting 0.957444429397583
results  0.00016812373907195696 mistakes in test 0.02488231338264963 for c 0.001 for d 6 for fold  3 iter  19
time taken training 13.023967504501343
time taken predicting 0.2872035503387451
time taken predicting 0.969191312789917
results  0.0003362474781439139 mistakes in test 0.02824478816408877 for c 0.001 for d 6 for fold  4

In [28]:
print(bestResultSvm)

[[3.00000000e+00 1.00000000e-03 2.55548083e-02]
 [4.00000000e+00 1.00000000e+00 2.39408204e-02]
 [3.00000000e+00 1.00000000e-02 2.40753194e-02]
 [4.00000000e+00 1.00000000e+00 2.44788164e-02]
 [4.00000000e+00 1.00000000e-02 2.43443174e-02]
 [4.00000000e+00 1.00000000e-02 2.50168124e-02]
 [4.00000000e+00 1.00000000e+00 2.35373235e-02]
 [4.00000000e+00 1.00000000e-03 2.19233356e-02]
 [4.00000000e+00 1.00000000e-03 2.29993275e-02]
 [4.00000000e+00 1.00000000e-02 2.38063215e-02]
 [4.00000000e+00 1.00000000e-02 2.27303295e-02]
 [4.00000000e+00 1.00000000e-03 2.42098184e-02]
 [4.00000000e+00 1.00000000e+00 2.32683255e-02]
 [4.00000000e+00 1.00000000e-02 2.43443174e-02]
 [4.00000000e+00 1.00000000e+00 2.42098184e-02]
 [4.00000000e+00 1.00000000e-02 2.34028245e-02]
 [4.00000000e+00 1.00000000e-02 2.43443174e-02]
 [4.00000000e+00 1.00000000e-03 2.39408204e-02]
 [4.00000000e+00 1.00000000e-03 2.20578346e-02]
 [3.00000000e+00 1.00000000e+00 2.25958305e-02]]


In [25]:
dbest = bestResultSvm[:,0].reshape(-1)
cbest = bestResultSvm[:,1].reshape(-1)
start_time_main = time.time()
#ori_train,ori_test = read_data(datas)

resultsBestCrossSvm = np.zeros([len(dbest),2])
for diter, d in enumerate(dbest):
    #print(a)
    # classifiers = clearGLBcls(train,10)
    #print(classifiers.shape)
    c = cbest[diter]
    
    train = shuffling(ori_train)
    test = shuffling(ori_test)

    start_time = time.time()
    #amin loop to predict using One vs one
    a, betas = train_svm(combi,train,d, c)

    kernel_test = kerval(train[:,1:].T, test[:,1:].T, d)
    pred_result = preds_data(combi,kernel_test,test,train,a,betas)

    pred_final = np.zeros([test.shape[0]])
    for i,pred_data in enumerate(pred_result):
        pred_final[i] = pred_class(pred_data, np.array(combi))

    avg_test_err = np.mean(pred_final != test[:,0])
    kernel_train = kerval(train[:,1:].T, train[:,1:].T, d)
    pred_result = preds_data(combi,kernel_train,train,train,a,betas)

    pred_final = np.zeros([train.shape[0]])
    for i,pred_data in enumerate(pred_result):
        pred_final[i] = pred_class(pred_data, np.array(combi))
    avg_train_err = np.mean(pred_final != train[:,0])
    #end of one vs one prediction
    print("results ",avg_train_err, "mistakes in test",avg_test_err,"for c", c, "for d",d)


    

    #print("--- %s seconds ---" , (time.time() - start_time_epoch), "iter",b)
    resultsBestCrossSvm[diter,:] = np.array([avg_train_err,avg_test_err])
    print("--- %s seconds ---" , (time.time() - start_time), "for d*",diter)
print("--- %s seconds ---" , (time.time() - start_time_main))

time taken training 19.583230018615723
time taken predicting 0.47922730445861816
time taken predicting 1.6452116966247559
results  0.0014788921753159452 mistakes in test 0.02849462365591398 for c 0.001 for d 3.0
--- %s seconds --- 25.97563672065735 for d* 0
time taken training 18.579772233963013
time taken predicting 0.461775541305542
time taken predicting 1.6762514114379883
results  0.00040333422963162143 mistakes in test 0.02204301075268817 for c 1.0 for d 4.0
--- %s seconds --- 24.85861849784851 for d* 1
time taken training 18.666461944580078
time taken predicting 0.44585275650024414
time taken predicting 1.6800816059112549
results  0.0017477816617370262 mistakes in test 0.025806451612903226 for c 0.01 for d 3.0
--- %s seconds --- 24.955713033676147 for d* 2
time taken training 18.666316270828247
time taken predicting 0.5545146465301514
time taken predicting 1.7663295269012451
results  0.00040333422963162143 mistakes in test 0.023118279569892472 for c 1.0 for d 4.0
--- %s seconds --

In [26]:
dbestavg = np.mean(bestResultSvm[:,0])
dbeststd = np.std(bestResultSvm[:,0])

cbestavg = np.mean(bestResultSvm[:,1])
cbeststd = np.std(bestResultSvm[:,1])

errorTestAvg = np.mean(resultsBestCrossSvm[:,1])
errorStdAvg = np.std(resultsBestCrossSvm[:,1])
print(f"d* average {dbestavg} with std deviation {dbeststd}")

print(f"c* average {cbestavg} with std deviation {cbeststd}")
print(f"error test average {errorTestAvg} with std deviation {errorStdAvg}")

d* average 3.85 with std deviation 0.3570714214271425
c* average 0.3043 with std deviation 0.4554578026557455
error test average 0.02424731182795699 with std deviation 0.00453943041458316


In [40]:
print(resultsBestCrossSvm)

[[0.00026889 0.01827957]
 [0.00026889 0.01989247]]
